version: '3'
services:
  mongodb:
    image: mongo:4.0.1
    container_name: mongodb-confusion-server
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: confusion-server
